export const pipelineConstants = {
    CREATE_FLASH: 'CREATE_FLASH_PIPELINES',
    PIPELINE_CHANGE_TITLE: "PIPELINE_CHANGE_TITLE",
    PIPELINE_CHANGE_CATEGORY: "PIPELINE_CHANGE_CATEGORY",
    PIPELINE_CHANGE_CODE: "PIPELINE_CHANGE_CODE",
    PIPELINE_CHANGE_ACTIVE: "PIPELINE_CHANGE_ACTIVE",
    PIPELINE_CHANGE_NOTES: "PIPELINE_CHANGE_NOTES",
    PIPELINE_SET_LOADING: "PIPELINE_SET_LOADING",
    PIPELINE_SAVE_SUCCESS: "PIPELINE_SAVE_SUCCESS",
    PIPELINE_HAS_ERROR: "PIPELINE_HAS_ERROR",
    PIPELINE_DETAIL_DATA_TO_STATE: "PIPELINE_DETAIL_DATA_TO_STATE",
    PIPELINE_EDIT_MODE: "PIPELINE_EDIT_MODE",
    PIPELINE_CLEAR_STATE: "PIPELINE_CLEAR_STATE",
    SAVE: 'SAVE_PIPELINES'
};
